### ISSUE TITLE
Conflict with other Plugins 

### ISSUE THREAD

**Issue by TimidScript** [robnyman/firefinder#7]
Firefinder tab goes missing if I have GreaseMonkey and AdBlock Plus installed. Disable either GM or AP and the Firefinder tab reappears again. 

Tested it on a clean profile and just installed Firebug, Firefinder, GM and AP. 

(Raised also in GM https://github.com/greasemonkey/greasemonkey/issues/2445)

**Comment by robnyman** [comment]
Thanks for the report. It's been many years since I worked on Firefinder so currently it's just supported as-is. The collision between extensions like that sometimes unfortunately happens, and not sure how to address that. :-/

If you know what do to do, I'd be more than happy to accept a pull request.

**Comment by TimidScript** [comment]
Above my level of "expertise". It's a shame no one has picked this up, it's a brilliant addon.
Thanks

**Comment by robnyman** [comment]
Got it. And thanks, glad you like it!
